// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sun May 12 15:18:27 2024

control_unit control_unit_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.opcodeIn(opcodeIn_sig) ,	// input [5:0] opcodeIn_sig
	.address_method(address_method_sig) ,	// input [1:0] address_method_sig
	.clkOut(clkOut_sig) ,	// output  clkOut_sig
	.rx_recv(rx_recv_sig) ,	// input  rx_recv_sig
	.rz_recv(rz_recv_sig) ,	// input  rz_recv_sig
	.increment(increment_sig) ,	// output [2:0] increment_sig
	.alu_opsel(alu_opsel_sig) ,	// output [5:0] alu_opsel_sig
	.ld_r(ld_r_sig) ,	// output  ld_r_sig
	.clr_z_flag(clr_z_flag_sig) ,	// output  clr_z_flag_sig
	.dm_wr(dm_wr_sig) ,	// output  dm_wr_sig
	.wren(wren_sig) ,	// output  wren_sig
	.rf_sel(rf_sel_sig) ,	// output [3:0] rf_sel_sig
	.rf_init(rf_init_sig) ,	// output  rf_init_sig
	.z(z_sig) ,	// output  z_sig
	.dpcr_lsb_sel(dpcr_lsb_sel_sig) ,	// output  dpcr_lsb_sel_sig
	.dpcr_wr(dpcr_wr_sig) 	// output  dpcr_wr_sig
);

